# Generated by Django 5.0 on 2024-01-28 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loventoutou", "0002_owner_breeding_name_alter_dog_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="owner",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="password",
            field=models.TextField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name="owner",
            name="mail_owner",
            field=models.CharField(
                default=None,
                max_length=255,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
