# Generated by Django 5.0 on 2024-05-20 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "loventoutou",
            "0003_owner_is_active_owner_is_staff_owner_last_login_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="id_user",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="owner",
            name="complete_address",
            field=models.CharField(max_length=250, verbose_name="adresse"),
        ),
        migrations.AlterField(
            model_name="owner",
            name="mail_owner",
            field=models.CharField(
                default=None,
                max_length=255,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="adresse mail",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="password",
            field=models.CharField(
                default=None, max_length=128, verbose_name="mot de passe"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro de téléphone doit contenir 10 chiffres.",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="siret_number",
            field=models.PositiveBigIntegerField(verbose_name="numéro de siret"),
        ),
    ]
