# Generated by Django 5.0 on 2024-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "loventoutou",
            "0004_dog_bio_owner_id_user_alter_owner_complete_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="id_user",
            field=models.IntegerField(),
        ),
    ]
