# Generated by Django 5.0 on 2024-05-20 10:40

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loventoutou", "0006_alter_owner_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="id_user",
            field=models.IntegerField(default=builtins.any),
        ),
    ]
