# Generated by Django 5.0 on 2024-05-20 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loventoutou", "0009_alter_owner_id_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="id_user",
        ),
    ]
