# Generated by Django 5.0 on 2024-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loventoutou", "0011_alter_owner_siret_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="bio",
        ),
    ]
