# Generated by Django 5.0 on 2024-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loventoutou", "0012_remove_dog_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
